### ISSUE TITLE
Win 7 64 - Crashing after I play a bit with the analyzed executable

### ISSUE THREAD

**Issue by jjgh** [frida/cryptoshark#3]
Don't know if it's due to the executable self-defense though :)

**Comment by oleavr** [comment]
Thanks for reporting! Did you try with the latest Frida code from git?

**Comment by hmartinh** [comment]
Hello. try to use this stuff with Java programm. And java crashed when i follow some thread or unfollow.

**Comment by jjgh** [comment]
@oleavr did you mean if I compiled it myself from latest sources? No, at the time I used the binary linked on the readme page.. but maybe you could provide an updated build? ;)

**Comment by oleavr** [comment]
Sorry for the long-time radio silence here. Finally some good news – CryptoShark is now back from the dead:
https://github.com/frida/cryptoshark/releases/tag/0.2.0
(Only macOS binaries available for now.)

The code tracing engine (Stalker) has improved a lot since 2015 so hopefully this is now fixed. Feel free to open a new issue at a later time if/when you get a chance to test the new version.

Cheers!
